services:
  evaluator:
    build:
      context: ./evaluator
      dockerfile: Dockerfile
    depends_on:
      - clusterer
    image: evaluator
    command:
      - "--url=host.docker.internal:${TOOL_PORT}"
    volumes:
      - ./evaluator/data:/app/data

  clusterer:
    build:
      context: ./tools/clusterer
      dockerfile: Dockerfile
    command:
      - "--port=${TOOL_PORT}"
    image: clusterer
    ports:
      - "${TOOL_PORT}:${TOOL_PORT}"
    environment:
      PORT: ${TOOL_PORT}
